Repository TOY-UX-TEAM/uuzz-frontend, pull requests merged in 2023-02, with the labels that each got.

#7 Library : 개발에 필요한 각종 라이브러리 설치 (#6)
  package-lock.json
  package.json
Labels: Library

#8 Feat : 공통 컴포넌트 작성 및 구조 설계 (#5)
  docs/folder.md
  public/favicon.ico
  public/index.html
  src/@types/type.ts
  src/App.css
  src/App.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Structure.tsx
  src/images/logo.png
  src/pages/Index/Index.tsx
  src/styles/GlobalStyles.tsx
Labels: Feature

#10 Docs : 기본 파일 구조 MD 작성 (#9)
  docs/folder.md
Labels: documentation

#11 Feat : 메인페이지 추가 (#4)
  package-lock.json
  src/@types/type.ts
  src/components/MainTitle.tsx
  src/components/Pagination.tsx
  src/pages/MainPage.tsx
Labels: Feature
